export enum ROUTER {
  LOGIN = '/login',
  ADMIN = '/admin',
  ADMIN_LOGIN = '/admin/login',
  ADMIN_SUBJECT = '/admin/subject',
  ADMIN_TEACHER = '/admin/teacher',
  ADMIN_DISCIPLINE = '/admin/discipline',
  ADMIN_ADMINISTRATION = '/admin/administration',
  ADMIN_EXAM = '/admin/exam',
  ADMIN_EXAM_KIT = '/admin/exam-kit',
  ADMIN_EXAM_SUBMISSION = '/admin/exam-submission',
  ADMIN_DOCUMENT = '/admin/document',
  HOMEPAGE = '/',
  EXAM_PAGE = '/exam',
  ABOUT = '/about',
  CONTACT = '/contact',
  EXAM_DETAIL_PAGE = '/exam/:examKitId',
  NEW_PAGE = '/news',
  DOCUMENT_PAGE = '/document',
  DOCUMENT_DETAIl_PAGE = '/document/:examId',
  STUDENT_INFO = '/student-info'
}